# Generated by Django 5.0.4 on 2024-04-23 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(max_length=100, verbose_name='Especialidades')),
                ('icone', models.ImageField(blank=True, null=True, upload_to='icones')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.CharField(max_length=50, verbose_name='CRM')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('rua', models.CharField(max_length=150, verbose_name='Rua')),
                ('barirro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('rg', models.ImageField(upload_to='rgs', verbose_name='RG')),
                ('cedula_indentidade_medica', models.ImageField(upload_to='cim')),
                ('foto', models.ImageField(upload_to='foto_perfil')),
                ('descrição', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('valor_consulta', models.FloatField(default=100)),
                ('especialidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medico.especialidades')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
