# Generated by Django 5.0.4 on 2024-04-26 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teste', models.CharField(max_length=100, verbose_name='teste')),
            ],
        ),
        migrations.RenameModel(
            old_name='Medico',
            new_name='DadosMedico',
        ),
        migrations.AddField(
            model_name='especialidades',
            name='teste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medico.teste'),
        ),
    ]
