# Generated by Django 5.0.4 on 2024-05-17 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_datasabertas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosmedico',
            old_name='barirro',
            new_name='bairro',
        ),
        migrations.RenameField(
            model_name='dadosmedico',
            old_name='descrição',
            new_name='descriçao',
        ),
    ]
