# Generated by Django 5.0.4 on 2024-05-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0005_rename_barirro_dadosmedico_bairro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosmedico',
            old_name='descriçao',
            new_name='descricao',
        ),
    ]
